"$schema" = 'https://starship.rs/config-schema.json'

format = """
$time\
$username$hostname\
$all\
$line_break$status$character"""

[time]
disabled = false
time_format = "%R"
style = "bold white"
format = '[$time ]($style)'

[status]
disabled = false
symbol = ""
format = "[$status ]($style)"
